# Generated by Django 3.2.4 on 2021-06-29 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagories',
            name='catagory',
            field=models.CharField(choices=[], default=1, max_length=100),
        ),
    ]
