# Generated by Django 3.2.4 on 2021-06-29 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs1', '0003_alter_catagories_catagory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagories',
            name='catagory',
            field=models.CharField(choices=[('all_jobs', 'All Jobs')], default=1, max_length=100),
        ),
    ]
