# Generated by Django 3.2.4 on 2021-06-29 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs1', '0004_alter_catagories_catagory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagories',
            name='catagory',
            field=models.CharField(choices=[('all_jobs', 'All Jobs'), ('private_tech_jobs', 'Private Tech Jobs'), ('private_non_tech_jobs', 'Private Non Tech Jobs'), ('part_time_jobs', 'Part Time Jobs'), ('govt_tech_jobs', 'Govt. Tech Jobs'), ('govt_non_tech_jobs', 'Govt. Non Tech Jobs'), ('internships', 'Internships'), ('competative_coding', 'Competative Coding'), ('free_courses', 'Free Courses'), ('certifications', 'Certifications')], default=1, max_length=100),
        ),
    ]
