# Generated by Django 3.2.4 on 2021-07-06 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs1', '0006_alter_catagories_catagory'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email_id', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=20)),
                ('profile', models.CharField(max_length=100)),
                ('prograrmming_language', models.CharField(max_length=200)),
                ('prefered_location', models.CharField(max_length=200)),
                ('exp_from', models.IntegerField()),
                ('exp_to', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='catagories',
            name='catagory',
            field=models.CharField(choices=[('all_jobs', 'All Jobs'), ('private_tech_jobs', 'Private Tech Jobs'), ('private_non_tech_jobs', 'Private Non Tech Jobs'), ('part_time_jobs', 'Part Time Jobs'), ('govt_tech_jobs', 'Govt. Tech Jobs'), ('govt_non_tech_jobs', 'Govt. Non Tech Jobs'), ('internships', 'Internships'), ('competative_coding', 'Competative Coding'), ('free_courses', 'Free Courses'), ('certifications', 'Certifications')], default=1, max_length=100),
        ),
    ]
