# Generated by Django 3.2.4 on 2021-07-10 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs1', '0007_auto_20210706_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email_id', models.CharField(max_length=60)),
                ('profile', models.CharField(max_length=100)),
                ('prograrmming_language', models.CharField(max_length=200)),
                ('prefered_location', models.CharField(max_length=200)),
                ('exp_from', models.IntegerField()),
                ('exp_to', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
