# Generated by Django 3.2.4 on 2021-07-10 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs1', '0009_auto_20210710_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogin',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userlogin',
            name='email_id',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email_id',
            field=models.CharField(max_length=60),
        ),
    ]
