# Generated by Django 3.2.4 on 2021-07-10 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs1', '0010_auto_20210710_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlogin',
            name='id',
        ),
        migrations.AlterField(
            model_name='userlogin',
            name='email_id',
            field=models.CharField(max_length=60, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs1.userlogin'),
        ),
    ]
