# Generated by Django 3.2.4 on 2021-07-11 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs1', '0011_auto_20210710_2302'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=100)),
                ('email_id', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='RecommendedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=100)),
                ('email_id', models.CharField(max_length=60)),
            ],
        ),
    ]
