# Generated by Django 3.2.4 on 2021-07-11 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs1', '0012_jobhistory_recommendedjob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobhistory',
            old_name='email_id',
            new_name='user_name',
        ),
        migrations.RenameField(
            model_name='recommendedjob',
            old_name='email_id',
            new_name='user_name',
        ),
        migrations.RenameField(
            model_name='userlogin',
            old_name='email_id',
            new_name='user_name',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_name',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='jobs1.userlogin'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email_id',
            field=models.CharField(max_length=60),
        ),
    ]
